const { DataTypes } = require('sequelize');

module.exports = (sequelize) => sequelize.define('courses', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  name: DataTypes.STRING,
  about: DataTypes.STRING,
  description: DataTypes.TEXT,
  singlePrice: DataTypes.FLOAT,
  anualPrice: DataTypes.FLOAT,
  image: DataTypes.STRING,
  instructor: DataTypes.STRING,
  banner: DataTypes.STRING,
  section1: DataTypes.TEXT,
  section1Videos: DataTypes.STRING,
  section1Lectures: DataTypes.STRING,
  section1Time: DataTypes.FLOAT,
  section2: DataTypes.TEXT,
  section2Videos: DataTypes.STRING,
  section2Lectures: DataTypes.STRING,
  section2Time: DataTypes.FLOAT,
  section3: DataTypes.TEXT,
  section3Videos: DataTypes.STRING,
  section3Lectures: DataTypes.STRING,
  section3Time: DataTypes.FLOAT,
  section4: DataTypes.TEXT,
  section4Videos: DataTypes.STRING,
  section4Lectures: DataTypes.STRING,
  section4Time: DataTypes.FLOAT,
  section5: DataTypes.TEXT,
  section5Videos: DataTypes.STRING,
  section5Lectures: DataTypes.STRING,
  section5Time: DataTypes.FLOAT,
  resource: DataTypes.STRING,
  cta1: DataTypes.STRING,
  temary: DataTypes.TEXT,
  skills: DataTypes.STRING,
  requirements: DataTypes.STRING,
  certificate: DataTypes.STRING,
  faqs: DataTypes.STRING,
  qualification: DataTypes.INTEGER,
  comments: DataTypes.TEXT,
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE,
});